#!/bin/bash
#SBATCH --partition=
#SBATCH --nodes=
#SBATCH --ntasks-per-node=
#SBATCH --mem=
#SBATCH --time=
#SBATCH --job-name=FILE_NAME


module purge
module load python
module load rosetta/2022.11


#clea PDB first 
#release chain B for design - no constraints here except for 3 terminal residues
python /opt/applications/rosetta/2022.11/gnu/main/tools/protein_tools/scripts/generate_atom_pair_constraint_file.py tmhop_mod5_initial.pdb constraints.cst --release_file release_chain_B.txt
