#!/bin/bash
#SBATCH --partition=
#SBATCH --nodes=
#SBATCH --ntasks-per-node=
#SBATCH --mem=
#SBATCH --time=
#SBATCH --job-name=FILE_NAME


module purge
module load python
module load rosetta/2022.11


#clea PDB first 
#python /opt/applications/rosetta/2022.11/gnu/main/tools/protein_tools/scripts/clean_pdb.py input_mod4_origin_renum.pdb 
python /gpfs/home/cmaillie/mravic_lab/tlr/desig_fr/rosetta_approach/scripts/gen_span_file.py tmhop_mod5_trim.pdb /opt/applications/rosetta/2022.11/gnu/main/
