#!/bin/bash
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --mem=125gb
#SBATCH --time=16-00:00:00
#SBATCH --job-name=af_rank3


module purge
module load python
module load rosetta/2022.11


#clea PDB first 
#python /opt/applications/rosetta/2022.11/gnu/main/tools/protein_tools/scripts/clean_pdb.py input_mod4_origin_renum.pdb 
python /gpfs/home/cmaillie/mravic_lab/tlr/desig_fr/rosetta_approach/scripts/gen_span_file.py tmhop_mod5_trim.pdb /opt/applications/rosetta/2022.11/gnu/main/
