#!/bin/bash
#SBATCH --partition=shared
#SBATCH --nodes=20
#SBATCH --ntasks-per-node=16
#SBATCH --mem=125gb
#SBATCH --time=16-00:00:00
#SBATCH --output=designgen2.out
#SBATCH --job-name=5_gen2

module purge
module load rosetta/2020.03.61102

mkdir -p tmab_tmhop5_gen2

mpirun `which rosetta_scripts.mpi.linuxgccrelease` \
-parser:protocol /gpfs/home/cmaillie/mravic_lab/tlr/desig_fr/rosetta_approach/scripts/design_TMab_v1.xml \
-in:file:s tmhop_mod5_trim.pdb \
-nstruct 800 \
-mp:setup:spanfiles tmhop_mod5_trim.span \
-relax:jump_move true \
-mp:lipids:composition POPC \
-packing:pack_missing_sidechains 1 \
-out:path:all tmab_tmhop5_gen2 \
-parser:script_vars cst_file=constraints.cst \
-parser:script_vars resfile=resfile_gen2.txt
